ENGINE = InnoDB
SHOW WARNINGS;

CREATE  TABLE IF NOT EXISTS PLAYER (
  PLAYER_ID BIGINT NOT NULL AUTO_INCREMENT ,
  PLAYER_NAME VARCHAR(100) NULL ,
  PRIMARY KEY (PLAYER_ID) ,
  UNIQUE INDEX UQ_PLAYER_ID_ (PLAYER_ID ASC) )
COMMENT = 'PLAYER CREATED';

CREATE  TABLE IF NOT EXISTS USER_CREDENTIAL (
  USER_ID BIGINT NOT NULL AUTO_INCREMENT ,
  USER_NAME VARCHAR(100) NULL ,
  USER_PASSWORD VARCHAR(100) NULL ,
  USER_EMAIL VARCHAR(100) NULL ,
  USER_ENABLED TINYINT(1) NULL ,
  USER_PASSWORD_CHANGED DATETIME NULL ,
  USER_LAST_LOGIN DATETIME NULL ,
  PLAYER_ID BIGINT NOT NULL ,
  
  PRIMARY KEY (USER_ID) ,
  UNIQUE INDEX UQ_USER_ID_ (USER_ID ASC),
  
  CONSTRAINT FK_USER_PLAYER
    FOREIGN KEY (PLAYER_ID )
    REFERENCES PLAYER (PLAYER_ID )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = 'USER CREATED';


ALTER TABLE PLAYER ADD PLAYER_LEVEL INTEGER;
ALTER TABLE PLAYER ADD PLAYER_EXPERIENCE INTEGER;
ALTER TABLE PLAYER ADD PLAYER_ESCENE INTEGER;
ALTER TABLE PLAYER ADD PLAYER_AIM INTEGER;
ALTER TABLE PLAYER ADD PLAYER_HIT_RECOVERY DOUBLE;
ALTER TABLE PLAYER ADD PLAYER_TOTAL_LIFE INTEGER;


CREATE  TABLE IF NOT EXISTS MISSION (
  MISSION_ID BIGINT NOT NULL AUTO_INCREMENT ,
  MISSION_NAME VARCHAR(100) NULL ,
  MISSION_DESCRIPTION VARCHAR(100) NULL ,
  MISSION_AMOUNT_OF_ZOMBIES_TO_KILL INTEGER NULL ,
  MISSION_AMOUNT_OF_TIME_TO_SURVIVE DOUBLE NULL ,
  MISSION_IMAGE VARCHAR(100) NULL ,
  
  PRIMARY KEY (MISSION_ID) ,
  UNIQUE INDEX UQ_MISSION_ID_ (MISSION_ID ASC) )
COMMENT = 'MISSION CREATED';

