CREATE  TABLE IF NOT EXISTS MISSION (
  MISSION_ID BIGINT NOT NULL AUTO_INCREMENT ,
  MISSION_NAME VARCHAR(100) NULL ,
  MISSION_DESCRIPTION VARCHAR(100) NULL ,
  MISSION_IMAGE VARCHAR(100) NULL ,
  MISSION_ORDER INTEGER NULL,
  MISSION_HAS_TO_SHOW BOOLEAN NULL,
  
  PRIMARY KEY (MISSION_ID) ,
  UNIQUE INDEX UQ_MISSION_ID_ (MISSION_ID ASC) )
COMMENT = 'MISSION CREATED';


CREATE  TABLE IF NOT EXISTS MISSION_TIME_TO_SURVIVE (
  MISSION_ID BIGINT,
  MISSION_AMOUNT_OF_TIME_TO_SURVIVE DOUBLE NULL ,
  
  PRIMARY KEY (MISSION_ID) ,
  CONSTRAINT FK_MISSION_TIME_TO_SURVIVE_MISSION
	FOREIGN KEY (MISSION_ID)
	REFERENCES MISSION (MISSION_ID )
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);

CREATE  TABLE IF NOT EXISTS MISSION_ZOMBIES_TO_KILL (
  MISSION_ID BIGINT,
    MISSION_AMOUNT_OF_ZOMBIES_TO_KILL INTEGER NULL ,
  
  PRIMARY KEY (MISSION_ID) ,
  CONSTRAINT FK_MISSION_ZOMBIES_TO_KILL_MISSION
	FOREIGN KEY (MISSION_ID)
	REFERENCES MISSION (MISSION_ID )
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);

CREATE  TABLE IF NOT EXISTS MISSION_COMPOSITE (
  MISSION_ID BIGINT,
  
  PRIMARY KEY (MISSION_ID) ,
  CONSTRAINT FK_COMPOSITE_MISSION_MISSION
	FOREIGN KEY (MISSION_ID)
	REFERENCES MISSION (MISSION_ID )
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);

CREATE  TABLE IF NOT EXISTS COMPOSITE_MISSION_SIMPLE_MISSION (
  MISSION_COMPOSITE_ID BIGINT,
  MISSION_ID BIGINT,
  
  PRIMARY KEY (MISSION_ID) ,
  PRIMARY KEY (MISSION_COMPOSITE_ID) ,
  
  CONSTRAINT FK_COMPOSITE_MISSION_SIMPLE_MISSION_MISSION_COMPOSITE
	FOREIGN KEY (MISSION_COMPOSITE_ID)
	REFERENCES MISSION_COMPOSITE (MISSION_ID )
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	
	CONSTRAINT FK_COMPOSITE_MISSION_SIMPLE_MISSION_MISSION
	FOREIGN KEY (MISSION_ID)
	REFERENCES MISSION (MISSION_ID )
	ON DELETE NO ACTION
	ON UPDATE NO ACTION	);

  